name: Node.js test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache modules
      uses: actions/cache@v3
      id: node_modules_cache
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: ${{ steps.node_modules_cache.outputs.cache-hit != 'true' }}
      run: npm i
    - name: Test Jest
      run: npm run test-jest
    - name: Test Mocha
      run: npm run test-mocha